- A/A.ino
- B/B.ino
Fix #1 by replacing commas with underscores.
> Escape commas from SSIDs

- A/A.ino
- B/B.ino
ParseUtils, unicode, and url were removed.
Update year in top-line comment.
> Remove unused dependencies

- A/A.ino
Add the ability to remove files.
It might be nice to add a confirmation to the UI or a recycle-bin function before release.
> Add a file delete button

- A/A.ino
bl.txt on the SD card can now contain MACs/SSIDs/BLE-names to not be logged.
This current implementation may over-block things since the search function used is quite loose. eg, if an SSID `a` is detected, it will be blocked if you have `abc` in your blocklist. This should be addressed before release.
> Add blocklist support

- A/A.ino
And other improvements to the LCD information during web interface mode, closes #33
> Show the web interface timeout on LCD

- A/A.ino
- B/B.ino
Patch for #37 with version 1.0.3
> Fix SIM800L lockup issue

- A/A.ino
- README.md
Hi, i changed as you requested the previous working title from `Portable Wardriver` to `wardriver.uk`.
> Changed working title to "wardriver.uk"

- A/A.ino
- B/B.ino
Closes #30 by fixing the DS18B20 communication
> Fix ds18b20

- A/A.ino
Include the date in the filename of downloaded files.
> Add date to filename

- A/A.ino
Fixes WPA2/3 logging, adds WAPI_PSK
> Improvements to encryption types

- A/A.ino
Also allow some default variables to be changed using the config file.
> Add config file support

- README.md
Updated the filename format based on #53 to show date format used. Added reference to the DEL option from #21 and #59
> Update README.md - filename format, DELete reference

- README.md
> Docs now reference bl.txt

- A/A.ino
Updates can now be installed by uploading a .bin file via the web interface. This feature is completed but not refined, further improvements need to made to the UX/UI. The online hash verification also needs to be implemented, in addition to downloading updates from a URL.
> Implement OTA updates

- A/A.ino
- B/B.ino
Trigger OTA updates to side B, from side A.
> OTA updates for side B

- A/A.ino
Note: The online service for verification is not yet implemented aside from PoC code, so this feature is not yet fully working.
The certificates used here will be changed before this feature is properly released, meaning this version will be unable to do online verifications in the near future.
> Implement online hash verification

- A/A.ino
Binaries can now be downloaded from the wardriver.uk backend directly.
Some small OTA update UX improvements.
> Implement OTA binary downloads

- A/A.ino
> Fix hash generation

- A/A.ino
Fixes #93 on Side A. Bumps version number.
> Significant scan performance improvement [side A]

- B/B.ino
The fix for hash generation was done on A, but was not completed on B. Adding the fix to B.
> Fix hash generation on B

- README.md
> Improve documentation regarding version numbers

- A/A.ino
Fixes #106 by closing files once they are no longer in use
> Close files when done

- B/B.ino
> Fix side B not always awaiting serial lock

- B/B.ino
Added parsing for additional strings generated by my new BW16 firmware. Needed to rearrange slightly to prevent false matches.
> Add additional parsing for BW16-Open-AT firmware.
